
import type { ReportData } from '../types';

export const getInitialMockData = (initialValues: Partial<ReportData> = {}): ReportData => ({
  reportId: initialValues.reportId || `TK-${new Date().getFullYear()}-XXX`,
  projectName: initialValues.projectName || '新项目',
  location: initialValues.location || '待设置',
  plantOverview: {
    address: '',
    coordinates: null,
    overviewPhotos: [],
    layoutMap: null,
    satelliteImage: null,
    traffic: {
      condition: 'basic',
      description: '',
      map: null,
    },
    riskZone: {
      types: ['high_temp'],
      customTypes: [],
      description: '',
      photos: [],
    },
    powerInfo: {
      usagePeriod: 'single_rest_daytime',
      priceType: 'industrial',
      voltage: '10kv',
      timeOfUsePrice: true,
      billStatus: 'partial',
      loadCurveStatus: 'pending',
      licenseStatus: 'full',
    },
    propertyInfo: {
      landCertStatus: 'full',
      propertyCertStatus: 'full',
      ownerType: 'self_owned',
    },
  },
  buildingRoofs: [
    {
      id: 'roof-1',
      name: '屋顶-1',
      area: 0,
      type: 'color_steel_tile',
      capacity: 0,
      birdView: null,
      orientation: 'south',
      coordinates: null, // Added field
      utilization: 'few_obstacles',
      obstacleTypes: ['vent', 'skylight'],
      obstacleImage: null,
      pollutionLevel: 'general',
      pollutionImage: null,
      structureType: 'steel_structure',
      structureImage: null,
      abnormalTypes: ['leak'],
      abnormalImage: null,
      abnormalDescription: '',
      surroundingDescription: '',
      surroundingImage: null,
    },
  ],
  electricalFacilities: {
    siteRoomImage: null,
    siteTransformerImage: null,
    siteSingleLineImage: null,
    siteEnvImage: null,
    subFacilities: [],
    incomingVoltage: '10kv',
    meteringVoltage: '0.4kv',
    switchStationLevel: '',
    transformerInfoJson: '[]',
    transformerDistImage: null,
    gridMode: 'full_on_grid',
    gridCabinetLocation: '',
    cableLayingMethods: ['cable_duct', 'bridge'],
    cablePathDescription: '',
    gridLevel: '0.4kv',
    gridSchemeDescription: '',
    gridAttention: '',
  },
  documentCollection: {
    plant_layout_map: 'partial',
    plant_pipeline_map: 'pending',
    plant_geology_report: 'none',
    building_design_spec: 'pending',
    building_construction_drawing: 'pending',
    structure_construction_drawing: 'pending',
    roof_hvac_map: 'none',
    roof_firefighting_map: 'none',
    license: 'full',
    land_cert: 'full',
    property_cert: 'full',
    power_bills_1yr: 'partial',
    load_curve_1yr: 'pending',
    elec_layout_map: 'pending',
    elec_design_spec: 'pending',
    hv_lv_system_diagram: 'partial',
    grounding_map: 'none',
    cable_routing_map: 'none',
    room_layout_map: 'pending',
  },
  ...initialValues
});
